on:
  workflow_dispatch:
  workflow_call:
    inputs:
      tmp_number:
        description: "Enter number for call"
        required: true
        type: number
        default: 1

env:
  FORCE_COLOR: "1"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Validate input
      run: |
        if [[ "${{ inputs.tmp_number }}" < 1 ]]; then
          echo "Number of instances cannot be less than 1"
          exit 1
        fi


    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.sha }}

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Run python script
      env:
        ENV_NUM: ${{ inputs.tmp_number }}
      run: |
        echo num=$ENV_NUM
        python tmp.py
